### ISSUE TITLE
Intake arm actuates when enabled

### ISSUE THREAD

**Issue by kyraha** [team3130/FRC3130-2016#1]
The intake arm remembers the last state before "disabled" and then restores it when "enabled". Disable resets all solenoids so the arm will always retract when "disabled". But it should stay there when enabled, for safety reasons. And all the logic should be designed assuming that.

**Comment by kyraha** [comment]
@CaelumCat @trevorgeng  @Moirai01 @INPUTCODE please consider this issue as an opportunity to learn the robot code. Ask questions in the comments when you need help. @Duckfan77 and @LoopedBard3 are not allowed to take on this issue but can answer questions.

**Comment by Duckfan77** [comment]
Fixed: https://github.com/team3130/Geneva/commit/4f013f424a2dfc215b14aca9562cc36c3b730a0f
