### ISSUE TITLE
Catapult reloads without firing

### ISSUE THREAD

**Issue by kyraha** [team3130/FRC3130-2016#2]
When the weapons officer is too fast slamming the "Fire" button it reloads without firing. The issue is that the fire command waits for intake and bincher to clear before firing the "Fire" cylinder. Can be fixed with a conditional "next command start" on the "waiting" flag.

**Comment by Duckfan77** [comment]
For fix, would it be as simple as checking if(!m_waiting) in the End() function and only starting the next command inside that statement?

**Comment by Duckfan77** [comment]
[Possible Fix](https://github.com/team3130/Geneva/commit/ca032b5dc961f8d4e1336e0d01620a27877ac793)
