### ISSUE TITLE
Flip the direction of the intake wheels

### ISSUE THREAD

**Issue by kyraha** [team3130/FRC3130-2016#5]
This issue needs more investigation why the directions are different on two robots. It could be the motor wiring flipped at some point or just motors themselves. In any case that needs to be resolved, preferably keeping the red/black connections correct, so the hardware on the two robots act exactly the same way and then the software updated accordingly.

**Comment by Duckfan77** [comment]
Will be done on the actual bot.

**Comment by kyraha** [comment]
Hardware fix: Black motor wire now got connected to the red supply wire and the red motor wire to the black supply. Ugly but works.
